# Generated by Django 3.2.4 on 2021-09-26 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptionist', models.CharField(blank=True, max_length=15, null=True)),
                ('appointment_Id', models.CharField(default=2021, max_length=8, null=True)),
                ('created', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False, max_length=5)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Treated', 'Treated'), ('New', 'New'), ('Pending', 'Pending')], default='New', max_length=9, null=True)),
            ],
            options={
                'verbose_name': 'Contact us Message',
                'verbose_name_plural': 'Contact us Messages',
                'ordering': ('-date_submitted',),
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Private', 'Private'), ('Family', 'Family')], default='Private', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Private', 'Private'), ('Family', 'Family')], default='Private', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_test', models.IntegerField(default=0, null=True)),
                ('admission', models.IntegerField(default=0, null=True)),
                ('injection', models.IntegerField(default=0, null=True)),
                ('medicine', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('confirmation', models.BooleanField(default=False, max_length=5)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hr')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.appointment')),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.receptionist')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
