# Generated by Django 3.2.4 on 2021-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receptionist',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
