# Generated by Django 3.2.4 on 2021-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210707_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
