# Generated by Django 3.2.4 on 2021-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointment_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receptionist',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
