# Generated by Django 3.2.4 on 2021-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_invoice_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_Id',
            field=models.CharField(default=2021, max_length=8, null=True),
        ),
    ]
