# Generated by Django 3.2.4 on 2021-07-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210707_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hr'),
        ),
    ]
