# Generated by Django 3.2.4 on 2021-07-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_invoice_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hr'),
        ),
    ]
