# Generated by Django 3.2.4 on 2021-07-07 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Private', 'Private'), ('Family', 'Family')], default='Private', max_length=20, null=True)),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Lab Technician', 'Lab Technician'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Admin', 'Admin')], default='Patient', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
