# Generated by Django 3.2.4 on 2021-07-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-created',), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
