# Generated by Django 3.2.4 on 2021-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210707_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='retainer',
        ),
        migrations.AddField(
            model_name='person',
            name='folder_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Staff', 'Staff')], default='Single', max_length=20, null=True),
        ),
    ]
