# Generated by Django 3.2.4 on 2021-07-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210711_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='folder_type',
            new_name='retainer',
        ),
    ]
