# Generated by Django 3.2.4 on 2021-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_folder_type_person_retainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Front Desk Officer', 'Front Desk Officer'), ('Doctor', 'Doctor'), ('Lab Technician', 'Lab Technician'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Admin', 'Admin')], default='Patient', max_length=20, null=True),
        ),
    ]
