# Generated by Django 3.2.4 on 2021-09-26 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Dialysis', 'Dialysis'), ('Radiology', 'Radiology'), ('Staff', 'Staff')], default='Single', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Staff', 'Staff')], default='Single', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Staff', 'Staff')], default='Single', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='LabScientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Staff', 'Staff')], default='Single', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Technician',
                'verbose_name_plural': 'Lab Technicians',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('retainer', models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Staff', 'Staff')], default='Single', max_length=20, null=True)),
                ('busy', models.BooleanField(default=False, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_symptoms', models.TextField(max_length=255)),
                ('test_result', models.TextField(max_length=255)),
                ('injection_dosage', models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Injection Dosage')),
                ('injection_how', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long? Day(s)')),
                ('tablet_dosage', models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Tablet Dosage')),
                ('tablet_how', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long? Day(s)')),
                ('syrup_dosage', models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Syrup Dosage')),
                ('syrup_how', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long? Day(s)')),
                ('suppository_dosage', models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Suppository Dosage')),
                ('suppository_how', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long? Day(s)')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.appointment')),
                ('injection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.injection')),
                ('lab_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.labscientist', verbose_name='Lab Technician')),
                ('suppository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.suppository')),
                ('syrup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.syrup')),
                ('tablet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tablet')),
            ],
            options={
                'verbose_name': "Patients' History",
                'verbose_name_plural': "Patients' Histories",
                'ordering': ('-created',),
            },
        ),
    ]
