# Generated by Django 3.2.4 on 2021-09-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
