# Generated by Django 3.2.4 on 2021-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='retainer',
            field=models.CharField(choices=[('Private', 'Private'), ('Family', 'Family')], default='Private', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
