# Generated by Django 3.2.4 on 2021-07-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20210707_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='lab_technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.labscientist'),
        ),
    ]
