# Generated by Django 3.2.4 on 2021-07-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20210630_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labscientist',
            options={'ordering': ('user',), 'verbose_name': 'Lab Technician', 'verbose_name_plural': 'Lab Technicians'},
        ),
    ]
