# Generated by Django 3.2.4 on 2021-07-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_alter_labscientist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='lab_technician',
        ),
    ]
