# Generated by Django 3.2.4 on 2021-07-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_auto_20210711_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='folder_type',
            new_name='retainer',
        ),
        migrations.RenameField(
            model_name='labscientist',
            old_name='folder_type',
            new_name='retainer',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='folder_type',
            new_name='retainer',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='folder_type',
            new_name='retainer',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='folder_type',
            new_name='retainer',
        ),
    ]
