# Generated by Django 3.2.5 on 2021-07-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_auto_20210711_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='retainer',
            field=models.CharField(choices=[('Single', 'Single'), ('Family', 'Family'), ('NHIS', 'NHIS'), ('HMO', 'HMO'), ('Dental', 'Dental'), ('OPD', 'OPD'), ('ANC', 'ANC'), ('Dialysis', 'Dialysis'), ('Radiology', 'Radiology'), ('Staff', 'Staff')], default='Single', max_length=20, null=True),
        ),
    ]
