# Generated by Django 3.2.5 on 2021-07-31 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_suppository_options'),
        ('treatment', '0010_alter_pharmacist_retainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.AddField(
            model_name='consultation',
            name='injection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.injection'),
        ),
    ]
