# Generated by Django 3.2.5 on 2021-08-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_suppository_options'),
        ('treatment', '0011_auto_20210731_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='suppository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.suppository'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='syrup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.syrup'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tablet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tablet'),
        ),
    ]
