# Generated by Django 3.2.5 on 2021-08-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_suppository_options'),
        ('treatment', '0012_auto_20210801_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='injection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.injection'),
        ),
    ]
