# Generated by Django 3.2.5 on 2021-08-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0014_auto_20210801_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='dosage',
            field=models.CharField(choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=20, null=True),
        ),
    ]
