# Generated by Django 3.2.4 on 2021-08-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0018_auto_20210801_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='dosage',
            new_name='injection_dosage',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='how',
            new_name='injection_how',
        ),
    ]
