# Generated by Django 3.2.4 on 2021-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0019_auto_20210801_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='suppository_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='suppository_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='syrup_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='syrup_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tablet_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tablet_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True),
        ),
    ]
