# Generated by Django 3.2.4 on 2021-08-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0020_auto_20210801_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='injection_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Injection Dosage'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='injection_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long?'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='lab_technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.labscientist', verbose_name='Lab Technician'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='suppository_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Suppository Dosage'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='suppository_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long?'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='syrup_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Syrup Dosage'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='syrup_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long?'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='tablet_dosage',
            field=models.CharField(blank=True, choices=[('ods', 'ods'), ('bd', 'bd'), ('tds', 'tds'), ('wkly', 'wkly'), ('monthly', 'monthly')], default='ods', max_length=7, null=True, verbose_name='Tablet Dosage'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='tablet_how',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='1', max_length=3, null=True, verbose_name='How Long?'),
        ),
    ]
