# Generated by Django 3.2.4 on 2021-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0021_auto_20210801_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
