# Generated by Django 3.2.4 on 2021-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injection',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Type'),
        ),
    ]
