# Generated by Django 3.2.5 on 2021-07-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppository',
            options={'ordering': ('-created',), 'verbose_name': 'Suppository', 'verbose_name_plural': 'Suppositories'},
        ),
    ]
