# Generated by Django 3.2.5 on 2021-08-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_suppository_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
