# Generated by Django 3.2.4 on 2021-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_injection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppository',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='syrup',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Type'),
        ),
    ]
