# Generated by Django 3.2.4 on 2021-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210801_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injection',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
