# Generated by Django 3.2.4 on 2021-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210801_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppository',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='syrup',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
